# Generated by Django 5.2.4 on 2025-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="assignment4app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("", "Open this select menu"),
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
