# Generated by Django 5.2.4 on 2025-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment4app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment4app",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Choose gender"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
